version: '{build}'
image: Visual Studio 2019

environment:
  nodejs_version: 16

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

build_script:
  - md src\preview\core\bin\src\preview
  - md src\preview\core\bin\src\simulator
  - npm run setup:build

after_build:
  - ps: |
      Push-AppveyorArtifact "fuse-*.exe"

test_script:
  - echo TODO npm test
